name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua por 'master' se sua branch principal for 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Verifique se esta versão corresponde à versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Este é o diretório onde seu build está sendo gerado
